"""Television remote protocol interface. Future adapters stay out of the MVP."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from app.samsung.models import ConnectionHealth, PairingCredentials


@runtime_checkable
class TelevisionRemoteProtocol(Protocol):
    async def start_pairing(self) -> None: ...

    async def confirm_pin(self, pin: str) -> PairingCredentials: ...

    async def connect(self) -> None: ...

    async def send_key(self, key: str) -> None: ...

    async def disconnect(self) -> None: ...

    async def health(self) -> ConnectionHealth: ...


# Reserved for later milestones. Do not implement in this MVP:
# class TizenWebSocketRemote: ...
# class AndroidEmbeddedHSeriesRemote: ...
# class InfraredBridgeRemote: ...
# class BroadLinkInfraredBridge: ...
# class RaspberryPiInfraredTransmitter: ...
# class ESP32InfraredTransmitter: ...
